language: node_js
node_js:
  - "10.1"

branches:
  only:
    - master
    
before_install:
  - npm i -g npm@latest

jobs:
  include:
    - stage: build
      script: ng build ng-disposable -c production
      script: ng-inactivity-timer -c production
      
# script:
  # - ng build ng-disposable -c production
  # - ng build ng-inactivity-timer -c production

notifications:
  email:
    on_failure: change
    on_success: change
    
cache:
  directories:
    - "node_modules"
